# Generated by Django 5.1.4 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specialty', models.CharField(choices=[('general_medicine', 'General medicine'), ('cardiology', 'Cardiology'), ('oncology', 'Oncology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('surgery', 'Surgery'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('other', 'Other')], max_length=32)),
                ('deliverable_type', models.CharField(choices=[('research_paper', 'Research paper'), ('review_article', 'Review article'), ('case_report', 'Case report'), ('abstract', 'Abstract'), ('other', 'Other')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround_days', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
