# Generated by Django 5.1.4 on 2026-05-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['specialty'], name='listings_li_special_e904f5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['deliverable_type'], name='listings_li_deliver_97b7b6_idx'),
        ),
    ]
