# Generated by Django 5.1.4 on 2026-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='specialty',
            field=models.CharField(choices=[('addictologie', 'Addictologie'), ('anatomie_pathologique', 'Anatomie cytologie pathologique'), ('bacteriologie', 'Bactériologie et hygiène'), ('biochimie', 'Biochimie'), ('biologie', 'Biologie'), ('cardiologie', 'Cardiologie'), ('dermatologie', 'Dermatologie'), ('diabetologie', 'Diabétologie'), ('endocrinologie', 'Endocrinologie et nutrition'), ('epidemiologie', 'Epidémiologie clinique et santé publique'), ('gastroenterologie', 'Gastroentérologie et pancréatologie'), ('genetique', 'Génétique médicale'), ('gynecologie', 'Gynécologie'), ('hematologie', 'Hématologie'), ('hepatologie', 'Hépatologie'), ('immunologie', 'Immunologie'), ('neonatologie', 'Néonatologie et réanimation néonatale'), ('nephrologie', 'Néphrologie'), ('neurochirurgie', 'Neurochirurgie'), ('neurologie', 'Neurologie'), ('obstetrique', 'Obstétrique'), ('odontologie', 'Odontologie'), ('oncologie', 'Oncologie médicale'), ('ophtalmologie', 'Ophtalmologie'), ('orl', 'Oto-rhino-laryngologie (ORL)'), ('parasitologie', 'Parasitologie et mycologie'), ('pediatrie', 'Pédiatrie générale et infectiologie'), ('pharmacologie', 'Pharmacologie'), ('allergologie', 'Allergologie'), ('pneumologie', 'Pneumologie'), ('psychiatrie', 'Psychiatrie et psychologie'), ('radiologie', 'Radiologie'), ('rhumatologie', 'Rhumatologie'), ('urologie', 'Urologie'), ('virologie', 'Virologie'), ('autres', 'Autres')], max_length=32),
        ),
    ]
