# Generated by Django 5.1.4 on 2026-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deliverable_type',
            field=models.CharField(choices=[('protocole_recherche', 'Protocole de recherche'), ('vulgarisation', 'Vulgarisation scientifique'), ('synopsis_recherche', 'Synopsis de recherche'), ('resume_recherche', 'Résumé de recherche'), ('autres', 'Autres')], max_length=32),
        ),
    ]
