# Generated by Django 5.1.4 on 2026-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
