# Generated by Django 5.1.4 on 2026-06-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_suspended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deletion_requested_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspended_at',
        ),
    ]
