from django.db import models


class Specialty(models.TextChoices):
    ADDICTOLOGIE = "addictologie", "Addictologie"
    ANATOMIE_PATHOLOGIQUE = "anatomie_pathologique", "Anatomie cytologie pathologique"
    BACTERIOLOGIE = "bacteriologie", "Bactériologie et hygiène"
    BIOCHIMIE = "biochimie", "Biochimie"
    BIOLOGIE = "biologie", "Biologie"
    CARDIOLOGIE = "cardiologie", "Cardiologie"
    DERMATOLOGIE = "dermatologie", "Dermatologie"
    DIABETOLOGIE = "diabetologie", "Diabétologie"
    ENDOCRINOLOGIE = "endocrinologie", "Endocrinologie et nutrition"
    EPIDEMIOLOGIE = "epidemiologie", "Epidémiologie clinique et santé publique"
    GASTROENTEROLOGIE = "gastroenterologie", "Gastroentérologie et pancréatologie"
    GENETIQUE = "genetique", "Génétique médicale"
    GYNECOLOGIE = "gynecologie", "Gynécologie"
    HEMATOLOGIE = "hematologie", "Hématologie"
    HEPATOLOGIE = "hepatologie", "Hépatologie"
    IMMUNOLOGIE = "immunologie", "Immunologie"
    NEONATOLOGIE = "neonatologie", "Néonatologie et réanimation néonatale"
    NEPHROLOGIE = "nephrologie", "Néphrologie"
    NEUROCHIRURGIE = "neurochirurgie", "Neurochirurgie"
    NEUROLOGIE = "neurologie", "Neurologie"
    OBSTETRIQUE = "obstetrique", "Obstétrique"
    ODONTOLOGIE = "odontologie", "Odontologie"
    ONCOLOGIE = "oncologie", "Oncologie médicale"
    OPHTALMOLOGIE = "ophtalmologie", "Ophtalmologie"
    ORL = "orl", "Oto-rhino-laryngologie (ORL)"
    PARASITOLOGIE = "parasitologie", "Parasitologie et mycologie"
    PEDIATRIE = "pediatrie", "Pédiatrie générale et infectiologie"
    PHARMACOLOGIE = "pharmacologie", "Pharmacologie"
    ALLERGOLOGIE = "allergologie", "Allergologie"
    PNEUMOLOGIE = "pneumologie", "Pneumologie"
    PSYCHIATRIE = "psychiatrie", "Psychiatrie et psychologie"
    RADIOLOGIE = "radiologie", "Radiologie"
    RHUMATOLOGIE = "rhumatologie", "Rhumatologie"
    UROLOGIE = "urologie", "Urologie"
    VIROLOGIE = "virologie", "Virologie"
    AUTRES = "autres", "Autres"


class DeliverableType(models.TextChoices):
    PROTOCOLE_RECHERCHE = "protocole_recherche", "Protocole de recherche"
    VULGARISATION = "vulgarisation", "Vulgarisation scientifique"
    SYNOPSIS_RECHERCHE = "synopsis_recherche", "Synopsis de recherche"
    RESUME_RECHERCHE = "resume_recherche", "Résumé de recherche"
    AUTRES = "autres", "Autres"
