# Generated by Django 5.1.4 on 2026-06-08 13:06

import apps.messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.messaging.models.message_attachment_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
