# Generated by Django 5.1.4 on 2026-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_engagement_and_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
