# Generated by Django 5.2.15 on 2026-06-29 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('placed', 'Commande passée'), ('accepted', 'Commande acceptée'), ('declined', 'Commande refusée'), ('paid', 'Paiement séquestré'), ('delivered', 'Travail livré'), ('completed', 'Commande finalisée'), ('cancelled', 'Commande annulée'), ('refunded', 'Paiement remboursé'), ('released', 'Paiement versé au rédacteur'), ('document_added', 'Document ajouté')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
