# Generated by Django 5.2.15 on 2026-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('placed', 'Commande passée'), ('accepted', 'Commande acceptée'), ('declined', 'Commande refusée'), ('paid', 'Paiement séquestré'), ('delivered', 'Travail livré'), ('completed', 'Commande finalisée'), ('cancelled', 'Commande annulée'), ('refunded', 'Paiement remboursé'), ('released', 'Paiement versé au rédacteur'), ('document_added', 'Document ajouté'), ('revision_requested', 'Révision demandée')], max_length=32),
        ),
    ]
