# Generated by Django 5.1.4 on 2026-05-18 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='requests_board.request'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['specialty'], name='requests_bo_special_8f98c3_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='requests_bo_status_4f2cbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('request', 'writer'), name='unique_proposal_per_writer'),
        ),
    ]
